In [1]:
import tensorflow as tf
import numpy as np

In [17]:
with tf.device('/cpu:0'):
    label = tf.Variable([1,2,3])

In [26]:
init_op = tf.global_variables_initializer()
num_classes = 10
# Launch the graph in a session.
with tf.Session() as sess:
    # Run the Op that initializes global variables.
    indices = []
    for i in range(num_classes):
        indices.append(list(range(i)) + list(range(i + 1, num_classes)))
    _js = tf.constant(indices, dtype=tf.int32)
    
    sess.run(init_op)
    print(label.eval())
    batch_size = tf.shape(label)[0]
    print(batch_size.eval())
    i = tf.range(batch_size, dtype=tf.int32)
    print(i.eval())
    correct_idx = tf.stack([i, tf.cast(label, tf.int32)], axis=1)
    print(correct_idx.eval())
    
    wrong_idx = tf.stack([
        tf.tile(tf.reshape(i, [batch_size, 1]), [1, num_classes - 1]),
        tf.gather(_js, label),
    ], axis=2)
    print(wrong_idx.eval())

[1 2 3]
3
[0 1 2]
[[0 1]
 [1 2]
 [2 3]]
[[[0 0]
  [0 2]
  [0 3]
  [0 4]
  [0 5]
  [0 6]
  [0 7]
  [0 8]
  [0 9]]

 [[1 0]
  [1 1]
  [1 3]
  [1 4]
  [1 5]
  [1 6]
  [1 7]
  [1 8]
  [1 9]]

 [[2 0]
  [2 1]
  [2 2]
  [2 4]
  [2 5]
  [2 6]
  [2 7]
  [2 8]
  [2 9]]]


In [25]:
range(9)+range(9)

TypeError: unsupported operand type(s) for +: 'range' and 'range'