In [17]:
th=0.772
tht=0.9
thf=0.95
rst_file = '/home/macul/casia_image_17_19_mtcnn20.pkl'
with open(rst_file,'rb') as f:
    rst = pkl.load(f)
    rst = np.array(rst)
print(np.mean(rst,0), rst.shape[0])
print(np.sum(rst[:,0]<=th)/rst.shape[0])
print(np.sum(rst[:,0]<=1.0-thf)/rst.shape[0])
print(np.sum(rst[:,0]>tht)/rst.shape[0])

[0.22243643 0.4079176  0.36964527] 1937
0.9261744966442953
0.42746515229736703
0.030459473412493547


In [2]:
import numpy as np
import pickle as pkl

In [18]:
rst_file = '/home/macul/casia_screen_17_19_mtcnn20.pkl'
with open(rst_file,'rb') as f:
    rst = pkl.load(f)
    rst = np.array(rst)
print(np.mean(rst,0), rst.shape[0])
print(np.sum(rst[:,0]<=th)/rst.shape[0])
print(np.sum(rst[:,0]<=1.0-thf)/rst.shape[0])
print(np.sum(rst[:,0]>tht)/rst.shape[0])

[0.06758531 0.43412152 0.4982922 ] 1720
0.9976744186046511
0.6680232558139535
0.0005813953488372093


In [23]:
th=0.885
tht=0.96
thf=0.95
rst_file = '/home/macul/casia_image_16_10_mtcnn20.pkl'
with open(rst_file,'rb') as f:
    rst = pkl.load(f)
    rst = np.array(rst)
print(np.mean(rst,0), rst.shape[0])
print(np.sum(rst[:,0]<=th)/rst.shape[0])
print(np.sum(rst[:,0]<=1.0-thf)/rst.shape[0])
print(np.sum(rst[:,0]>tht)/rst.shape[0])

[0.18713544 0.50995964 0.30290538] 1937
0.9514713474445018
0.4661848218895199
0.022715539494062985


In [20]:
rst_file = '/home/macul/casia_screen_16_10_mtcnn20.pkl'
with open(rst_file,'rb') as f:
    rst = pkl.load(f)
    rst = np.array(rst)
print(np.mean(rst,0), rst.shape[0])
print(np.sum(rst[:,0]<=th)/rst.shape[0])
print(np.sum(rst[:,0]<=1.0-thf)/rst.shape[0])
print(np.sum(rst[:,0]>tht)/rst.shape[0])

[0.09158415 0.28926352 0.6191523 ] 1720
0.9936046511627907
0.7930232558139535
0.0029069767441860465


In [31]:
th=0.885
tht=0.96
thf=0.95
rst_file = '/home/macul/dgx_casia_image_2_7_mtcnn20.pkl'
with open(rst_file,'rb') as f:
    rst = pkl.load(f)
    rst = np.array(rst)
print(np.mean(rst,0), rst.shape[0])
print(np.sum(rst[:,0]<=th)/rst.shape[0])
print(np.sum(rst[:,0]<=1.0-thf)/rst.shape[0])
print(np.sum(rst[:,0]>tht)/rst.shape[0])

[0.233869   0.6052027  0.16092801] 1937
0.9292720702116676
0.46360351058337634
0.03149199793495096


In [33]:
th=0.885
tht=0.96
thf=0.95
rst_file = '/home/macul/casia_image_2_20_mtcnn20.pkl'
with open(rst_file,'rb') as f:
    rst = pkl.load(f)
    rst = np.array(rst)
print(np.mean(rst,0), rst.shape[0])
print(np.sum(rst[:,0]<=th)/rst.shape[0])
print(np.sum(rst[:,0]<=1.0-thf)/rst.shape[0])
print(np.sum(rst[:,0]>tht)/rst.shape[0])

[0.233869   0.6052027  0.16092801] 1937
0.9292720702116676
0.46360351058337634
0.03149199793495096


In [27]:
rst_file = '/home/macul/dgx_casia_screen_2_7_mtcnn20.pkl'
with open(rst_file,'rb') as f:
    rst = pkl.load(f)
    rst = np.array(rst)
print(np.mean(rst,0), rst.shape[0])
print(np.sum(rst[:,0]<=th)/rst.shape[0])
print(np.sum(rst[:,0]<=1.0-thf)/rst.shape[0])
print(np.sum(rst[:,0]>tht)/rst.shape[0])

[0.22476439 0.4357772  0.33945835] 1720
0.9418604651162791
0.4994186046511628
0.019767441860465116


In [17]:
th=0.5
tht=0.9
thf=0.95
rst_file = '/home/macul/casia_image_13_6.pkl'
with open(rst_file,'rb') as f:
    rst = pkl.load(f)
    rst = np.array(rst)
print(np.mean(rst,0), rst.shape[0])
print(np.sum(rst[:,0]<=th)/rst.shape[0])
print(np.sum(rst[:,0]<=1.0-thf)/rst.shape[0])
print(np.sum(rst[:,0]>tht)/rst.shape[0])

[0.2918521  0.6084767  0.09967159] 1582
0.7338811630847029
0.3558786346396966
0.08217446270543616


In [18]:
rst_file = '/home/macul/casia_screen_13_6.pkl'
with open(rst_file,'rb') as f:
    rst = pkl.load(f)
    rst = np.array(rst)
print(np.mean(rst,0), rst.shape[0])
print(np.sum(rst[:,0]<=th)/rst.shape[0])
print(np.sum(rst[:,0]<=1.0-thf)/rst.shape[0])
print(np.sum(rst[:,0]>tht)/rst.shape[0])

[0.09103951 0.7571555  0.15180524] 1660
0.9493975903614458
0.6716867469879518
0.0030120481927710845


In [30]:
th=0.5
tht=0.9
thf=0.95
rst_file = '/home/macul/dgx_MSU_neg_2_7_mtcnn20_pb.pkl'
with open(rst_file,'rb') as f:
    rst = pkl.load(f)
    rst = np.array(rst)
print(np.mean(rst,0), rst.shape[0])
print(np.sum(rst[:,0]<=th)/rst.shape[0])
print(np.sum(rst[:,0]<=1.0-thf)/rst.shape[0])
print(np.sum(rst[:,0]>tht)/rst.shape[0])

[0.6160527  0.30601195 0.07793532] 2803
0.3738851230824117
0.13877987870139136
0.4070638601498395


0.665862969660438


In [13]:
print(rst.shape)

(4977, 3)
