In [2]:
import numpy as np
import pickle as pkl

In [266]:
th=0.9667
tht=0.98
thf=0.8
rst_file = '/home/macul/NUAA_Client_23_7_mtcnn20.pkl'
with open(rst_file,'rb') as f:
    rst = pkl.load(f)
    rst = np.array(rst)
print(np.mean(rst,0), rst.shape[0])
print(np.sum(rst[:,0]>th)/rst.shape[0])
print(np.sum(rst[:,0]>tht)/rst.shape[0])
print(np.sum(rst[:,0]<=1.0-thf)/rst.shape[0])

[0.91955405 0.06840576 0.01204035] 5063
0.6999802488643097
0.6225557969583251
0.03199683981828955


In [267]:
rst_file = '/home/macul/NUAA_Imposter_23_7_mtcnn20.pkl'
with open(rst_file,'rb') as f:
    rst = pkl.load(f)
    rst = np.array(rst)
print(np.mean(rst,0), rst.shape[0])
print(np.sum(rst[:,0]<=th)/rst.shape[0])
print(np.sum(rst[:,0]<=1.0-thf)/rst.shape[0])
print(np.sum(rst[:,0]>tht)/rst.shape[0])

[0.37764722 0.47264728 0.14970551] 7148
0.9251538891997761
0.4809736989367655
0.050923335198656966


In [281]:
th=0.885
tht=0.96
thf=0.95
rst_file = '/home/macul/dgx_NUAA_Client_2_7_mtcnn20.pkl'
with open(rst_file,'rb') as f:
    rst = pkl.load(f)
    rst = np.array(rst)
print(np.mean(rst,0), rst.shape[0])
print(np.sum(rst[:,0]>th)/rst.shape[0])
print(np.sum(rst[:,0]>tht)/rst.shape[0])
print(np.sum(rst[:,0]<=1.0-thf)/rst.shape[0])

[0.82767665 0.16328818 0.00903604] 5063
0.7003752715781157
0.5747580485877938
0.04206991902034367


In [282]:
rst_file = '/home/macul/dgx_NUAA_Imposter_2_7_mtcnn20.pkl'
with open(rst_file,'rb') as f:
    rst = pkl.load(f)
    rst = np.array(rst)
print(np.mean(rst,0), rst.shape[0])
print(np.sum(rst[:,0]<=th)/rst.shape[0])
print(np.sum(rst[:,0]<=1.0-thf)/rst.shape[0])
print(np.sum(rst[:,0]>tht)/rst.shape[0])

[0.239937   0.6537407  0.10632367] 7148
0.9064073866815893
0.5065752658086178
0.048405148293228874


In [95]:
th=0.857
tht=0.9
thf=0.96
rst_file = '/home/macul/NUAA_Client_16_10_mtcnn20.pkl'
with open(rst_file,'rb') as f:
    rst = pkl.load(f)
    rst = np.array(rst)
print(np.mean(rst,0), rst.shape[0])
print(np.sum(rst[:,0]>th)/rst.shape[0])
print(np.sum(rst[:,0]>tht)/rst.shape[0])
print(np.sum(rst[:,0]<=1.0-thf)/rst.shape[0])

[0.8438311  0.11575648 0.04041336] 5063
0.7009678056488248
0.6369741260122457
0.010665613272763184


In [96]:
rst_file = '/home/macul/NUAA_Imposter_16_10_mtcnn20.pkl'
with open(rst_file,'rb') as f:
    rst = pkl.load(f)
    rst = np.array(rst)
print(np.mean(rst,0), rst.shape[0])
print(np.sum(rst[:,0]<=th)/rst.shape[0])
print(np.sum(rst[:,0]<=1.0-thf)/rst.shape[0])
print(np.sum(rst[:,0]>tht)/rst.shape[0])

[0.23597474 0.63629824 0.12772645] 7148
0.8954952434247342
0.4679630665920537
0.08351986569669838


In [64]:
th=0.5
tht=0.9
thf=0.95
rst_file = '/home/macul/NUAA_Client_13_6.pkl'
with open(rst_file,'rb') as f:
    rst = pkl.load(f)
    rst = np.array(rst)
print(np.mean(rst,0), rst.shape[0])
print(np.sum(rst[:,0]>th)/rst.shape[0])
print(np.sum(rst[:,0]>tht)/rst.shape[0])
print(np.sum(rst[:,0]<=1.0-thf)/rst.shape[0])

[0.7022722 0.2731743 0.0245539] 4977
0.7166968053044003
0.5312437211171388
0.10026120152702431


In [65]:
rst_file = '/home/macul/NUAA_Imposter_13_6.pkl'
with open(rst_file,'rb') as f:
    rst = pkl.load(f)
    rst = np.array(rst)
print(np.mean(rst,0), rst.shape[0])
print(np.sum(rst[:,0]<=th)/rst.shape[0])
print(np.sum(rst[:,0]<=1.0-thf)/rst.shape[0])
print(np.sum(rst[:,0]>tht)/rst.shape[0])

[0.28950644 0.6661567  0.04433804] 6990
0.7310443490701002
0.4150214592274678
0.09985693848354793


In [68]:
th=0.65
tht=0.9
thf=0.95
rst_file = '/home/macul/MSU_pos_17_19.pkl'
with open(rst_file,'rb') as f:
    rst = pkl.load(f)
    rst = np.array(rst)
print(np.mean(rst,0), rst.shape[0])
print(np.sum(rst[:,0]>th)/rst.shape[0])
print(np.sum(rst[:,0]>tht)/rst.shape[0])
print(np.sum(rst[:,0]<=1.0-thf)/rst.shape[0])

[0.8050817  0.10334557 0.09157287] 1035
0.8009661835748793
0.6289855072463768
0.04541062801932367


In [69]:
rst_file = '/home/macul/MSU_neg_17_19.pkl'
with open(rst_file,'rb') as f:
    rst = pkl.load(f)
    rst = np.array(rst)
print(np.mean(rst,0), rst.shape[0])
print(np.sum(rst[:,0]<=th)/rst.shape[0])
print(np.sum(rst[:,0]<=1.0-thf)/rst.shape[0])
print(np.sum(rst[:,0]>tht)/rst.shape[0])

[0.45074007 0.2856322  0.26362762] 2804
0.6169757489300999
0.21041369472182597
0.21112696148359486


0.665862969660438


In [13]:
print(rst.shape)

(4977, 3)
